feat(back): #653.1 proxy and file descriptor
- Mutations to upload files to integrates sometimes hang-out,
  when they are retried, the file descriptor is already at EOF,
  causing the retried request to operate over nothing, raising
  ValueError: bla bla I/O error
- Fix that, and restore the proxy mechanism to intercept with burp
  and develop/debug like a pro
- Refac code removing unnecesary things

Close #653